### ISSUE TITLE
Failing backport disables further backports

### ISSUE THREAD

**Issue by mbernasocchi** [tibdex/github-backport#10]
when a PR is tagged to be backported to multiple branches if one of the backports fails the others are not executed and there is no message by backport bot.

examples can be found here 
- https://github.com/qgis/QGIS/pull/9691#issuecomment-480734499 
- https://github.com/qgis/QGIS/pull/30071

removing and readding the labels will trigger further backports. also, it seems that the order with which the labels are set to the PR might be relevant. here an example where one bp failed and one succeeded.
- https://github.com/qgis/QGIS/pull/30869

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this library anymore](https://github.com/tibdex/github-backport/commit/b17d162c7a3a0be5e3eaba2b54c9a2541d77ee66).
