### ISSUE TITLE
Update existing PR instead of throwing "Reference already exists" error

### ISSUE THREAD

**Issue by sorenlouv** [tibdex/github-backport#15]
If a backport pull request already exists `github-backport` throws an error with this message: "Reference already exists"
More details:
```jsonc
{
    "name": "HttpError",
    "status": 422,
    "headers": { ... },
    "request": {
        "method": "POST",
        "url": "https://api.github.com/repos/sqren/backport-demo/git/refs",
        "headers": {
            "accept": "application/vnd.github.v3+json",
            "user-agent": "octokit-rest.js/18.0.3 octokit-core.js/3.1.1 Node.js/10.21.0 (darwin; x64)",
            "authorization": "token [REDACTED]",
            "content-type": "application/json; charset=utf-8"
        },
        "body": "{\"ref\":\"refs/heads/backport-to-6.3\",\"sha\":\"e812829351c83be297d48ad7f4788ccf73c4de26\"}",
        "request": {}
    },
    "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
}
```

My suggestion is to handle this by updating the existing PR by [updating the reference](https://developer.github.com/v3/git/refs/#update-a-reference) with the latest sha from the base branch. This will make it possible to rebase an existing backport pull request.

This could perhaps be handled explicitly with a new option like `allowRebase`:
```ts
backportPullRequest({
  allowRebase: true
})
```

or `force`:
```ts
backportPullRequest({
  force: true
})
```

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this library anymore](https://github.com/tibdex/github-backport/commit/b17d162c7a3a0be5e3eaba2b54c9a2541d77ee66).
