### ISSUE TITLE
Typescript error: "Cannot use namespace 'Octokit' as a type." in `lib/index.d.ts`

### ISSUE THREAD

**Issue by sorenlouv** [tibdex/github-backport#16]
I'm getting the following error when running `tsc`
```
node_modules/github-backport/lib/index.d.ts:9:14 - error TS2709: Cannot use namespace 'Octokit' as a type.

9     octokit: Octokit;
               ~~~~~~~

Found 1 error.
```

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this library anymore](https://github.com/tibdex/github-backport/commit/b17d162c7a3a0be5e3eaba2b54c9a2541d77ee66).
