### ISSUE TITLE
Support backporting via forks (cross repo PRs)

### ISSUE THREAD

**Issue by sorenlouv** [tibdex/github-backport#17]
Sometimes the user performing the backport does not have push access to the primary repository, and the backport branch should therefore be created in a fork.

The [Github docs](https://octokit.github.io/rest.js/v18#pulls-create) specifies how to create a cross-repo PR:

> The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace head with a user like this: username:branch.

I therefore tried to specify the `head` as:
```js
backportPullRequest({
  head: `some-username:some-branch`,
});
```

But this throws an error:
```
refs/heads/some-username:some-branch is not a valid ref name.
```

**Comment by tibdex** [comment]
Thanks for reporting this but [I don't maintain this library anymore](https://github.com/tibdex/github-backport/commit/b17d162c7a3a0be5e3eaba2b54c9a2541d77ee66).
