### ISSUE TITLE
Checkout failing with Shippable

### ISSUE THREAD

**Issue by carlescufi** [tibdex/github-backport#8]
We've started using the app for the Zephyr Project:
https://github.com/zephyrproject-rtos/zephyr/pull/15515

But unfortunately our CI seems to stumble onto an unknown Git ref that we have no idea where is coming from:

https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/39643/1/console

```
git checkout -f cherry-pick-backport-15261-to-v1.14-branch-4c757f0a-e2e6-4102-b293-b0a458199a1c --
fatal: invalid reference: cherry-pick-backport-15261-to-v1.14-branch-4c757f0a-e2e6-4102-b293-b0a458199a1c
```

Any ideas as to where this unknown ref is being fed to Shippable?

**Comment by tibdex** [comment]
Hi Carles, you can take a look at https://github.com/tibdex/autorebase/issues/15 which is similar.

Tell me if it doesn't answer your question.

**Comment by carlescufi** [comment]
Hi @tibdex, thanks for the tip. This seems to work now.
